# Generated by Django 5.2.1 on 2025-05-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_appfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='telegram_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
